# Generated by Django 4.1.4 on 2022-12-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True, verbose_name='criado')),
                ('modified', models.DateField(auto_now=True, verbose_name='modificado')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('code', models.CharField(max_length=12, verbose_name='codigo')),
                ('description', models.CharField(max_length=30, verbose_name='descrição')),
                ('type', models.CharField(max_length=25, verbose_name='tipo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
