# Generated by Django 4.1.4 on 2022-12-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionmodel',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='connectionmodel',
            name='code',
            field=models.CharField(max_length=12, unique=True, verbose_name='codigo'),
        ),
    ]
