# Generated by Django 4.1.4 on 2022-12-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_connectionmodel_ip_alter_connectionmodel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionmodel',
            name='device',
            field=models.CharField(choices=[('D', 'desktop'), ('N', 'notebook'), ('T', 'tablet'), ('S', 'smartphone')], default='D', max_length=1, verbose_name='device'),
        ),
    ]
