# Generated by Django 4.1.4 on 2023-02-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_connectionmodel_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionmodel',
            name='mac',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='mac'),
        ),
        migrations.AddField(
            model_name='connectionmodel',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='nome'),
        ),
    ]
